# Assignment 0 
Name - Kinjal Kachi
Anumber - A20449343 

In [1]:
#Import all libraries used:
import numpy as np
from numpy import linalg as LA
import pandas as pd

In [2]:
#Define values:

A = np.array([[1], [2], [3]])
B = np.array([[4],[5],[6]])
C = np.array([[-1],[1],[3]])

In [6]:
#A.1)
a1 = 2*A - B
print("2A-B: \n",a1)

2A-B: 
 [[-2]
 [-1]
 [ 0]]


In [9]:
#A.2) 
a = LA.norm(A)
angle = np.arccos(A[0]/a)

print ('||A|| = \n', A)
print ('Angle of A relative to positive X-axis = ', np.degrees(angle))

||A|| = 
 [[1]
 [2]
 [3]]
Angle of A relative to positive X-axis =  [74.49864043]


In [12]:
#A.3
print("The unit vector in the direction of A :\n", A/np.sqrt(14))

the unit vector in the direction of A :
 [[0.26726124]
 [0.53452248]
 [0.80178373]]


In [15]:
#A.4
print("The direction cosines of A :\n")
print("cos alpha: ", np.arccos((A[0]/np.sqrt(14))))
print("cos beta: ", np.arccos((A[1]/np.sqrt(14))))
print("cos gamma: ", np.arccos((A[2]/np.sqrt(14))))

The direction cosines of A :

cos alpha:  [1.30024656]
cos beta:  [1.00685369]
cos gamma:  [0.64052231]


In [16]:
#A.5
print("A.B",np.dot(A.T,B))
print("B.A",np.dot(B.T,A))

A.B [[32]]
B.A [[32]]


In [23]:
# A.6

b = LA.norm(B)
a = LA.norm(B)
val_a = A/a
val_b = B/b
angle = np.arccos(np.dot((val_a).reshape(1, 3), val_b))
print ('Angle between A and B = ', np.degrees(angle))

Angle between A and B =  [[65.44387469]]


In [24]:
# A.7
print("Possible vectors perpendicular to A and B")
print("2,2,-2")
print("-1,-4,3")

Possible vectors perpendicular to A and B
2,2,-2
-1,-4,3


In [27]:
#A.8
reshaped_A = A.reshape(1,3)
reshaped_B = B.reshape(1,3)
print("AXB: ", np.cross(reshaped_A, reshaped_B))
print("BXA: ", np.cross(reshaped_B, reshaped_A))

AXB:  [[-3  6 -3]]
BXA:  [[ 3 -6  3]]


In [28]:
#A.9
print("Vector which is Perpendicular to both A and B is = [[-3  6 -3]]")
print("Dot product is zero")

Vector which is Perpendicular to both A and B is = [[-3  6 -3]]
Dot product is zero


In [31]:
#A.11
transposed_reshaped_A = A.reshape(3,1).transpose()
transposed_reshaped_B = B.reshape(3,1).transpose()
print("transpose(A)B: ", np.dot(transposed_reshaped_A, B.reshape(3,1)))
print("transpose(B)A: \n", np.dot(A.reshape(3,1), transposed_reshaped_B))

transpose(A)B:  [[32]]
transpose(B)A: 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [32]:
#Define values

A = np.matrix([[1,2,3], [4,-2,3], [0,5,-1]])
B = np.matrix([[1,2,1], [2,1,-4], [3,-2,1]])
C = np.matrix([[1,2,3], [4,5,6], [-1,1,3]])

In [36]:
#B.1)
b1 = 2*A - B
print ("2A-B: \n",b1)

2A-B: 
 [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [38]:
#B.2)
print ("A.B : \n", np.dot(A,B))
print ("A.B : \n", np.dot(B,A))

A.B : 
 [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
A.B : 
 [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [40]:
#B.3)
A.B = np.dot(A,B)
print ('transpose(AB) \n', A.B.transpose())
print ('transpose(B).transpose(A)\n', np.dot(B.transpose(),A.transpose()))

transpose(AB) 
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
transpose(B).transpose(A)
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [41]:
#B.4)
print ('|A| = ', LA.det(A))
print ('|C| = ', LA.det(C))

|A| =  54.999999999999964
|C| =  7.494005416219837e-16


In [44]:
#B.5
print("B forms an orthogonal set:")
reshaped_B0 = B[0].reshape(3,1)
reshaped_B1 = B[1].reshape(3,1)
reshaped_B2 = B[2].reshape(3,1)
print ('B1 B2 = ', np.dot(B[1],reshaped_B0))
print ('B2 B3 = ', np.dot(B[2],reshaped_B1))
print ('B3 B1 = ', np.dot(B[0],reshaped_B2))


B forms an orthogonal set:
B1 B2 =  [[0]]
B2 B3 =  [[0]]
B3 B1 =  [[0]]


In [45]:
#B.6

print ('A Inverse : \n', LA.inv(A))
print ('B Inverse : \n', LA.inv(B))

A Inverse : 
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
B Inverse : 
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [46]:
#Define Values:
A = np.array([[1,2], [3,2]])
B = np.array([[2,-2], [-2,5]])

In [48]:
#C.1

print ("Eigenvalues of A  ", LA.eig(A)[0])
print ("Eigenvectors of A  \n", LA.eig(A)[1])

Eigenvalues of A   [-1.  4.]
Eigenvectors of A  
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [52]:
#C.2 
print("V is eigenvector of A: \n", LA.eig(A)[1])
V = LA.eig(A)[1]
print("inv(V)AV: \n", np.dot(np.dot(LA.inv(V),A),V))

V is eigenvector of A: 
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
inv(V)AV: 
 [[-1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  4.0000000e+00]]


In [53]:
#C.3
print("Dot product between eigenvectors of A: ", np.dot(V[:,0].reshape(1,2),V[:,1]))

Dot product between eigenvectors of A:  [-0.19611614]


In [54]:
#C.4 
VB = LA.eig(B)[1]
print("Dot product between eigenvectors of VB: ", np.dot(VB[:,0].reshape(1,2),VB[:,1]))

Dot product between eigenvectors of VB:  [0.]


In [55]:
#C.5
print("The eigenvectors of B are perpendicular becuase their dot product is zero.")

The eigenvectors of B are perpendicular becuase their dot product is zero.
